from src.constants import *
from datetime import datetime

ROOT_DIR= ROOT_DIR_KEY

# Dataset URl

DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)

RAW_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURENT_TIME_STAMP,DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)

TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURENT_TIME_STAMP,DATA_INGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)

TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURENT_TIME_STAMP,DATA_INGESTION_INGESTED_DATA_DIR_KEY,TEST_DATA_DIR_KEY)


# Data Transformation

PREPROCESSING_OBJ_FILE=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFOMRATION_ARTIFACT,DATA_PREPROCESSED_DIR,DATA_TRANSFORMATION_PROCESSING_OBJ)

TRANSFORM_TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFOMRATION_ARTIFACT,DATA_TRANSFORM_DIR,TRANSFORM_TRAIN_DIR_KEY)

TRANSFORM_TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFOMRATION_ARTIFACT,DATA_TRANSFORM_DIR,TRANSFORM_TEST_DIR_KEY)

FEATURE_ENGG_OBJ_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFOMRATION_ARTIFACT,DATA_PREPROCESSED_DIR,"feature_engg.pkl")

# Model Training
MODEL_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,MODEL_TRAINER_KEY,MODEL_OBJECT)